### ISSUE TITLE
eb init failing

### ISSUE THREAD

**Issue by aelhennawy** [aws/aws-elastic-beanstalk-cli-setup#145]
**1. Please specify the following:**
 - OS: [e.g. OS X, Ubuntu, Windows, etc.]: ___
 - Shell (Bash, PowerShell, Zsh, etc.): ____

- [ ] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
Please describe the problem you are facing as precisely as possible in this section

I have an AWS Pipeline pulling my source code from github and deploying it to the Elastic Beanstalk using a buildspec.yml file 
The deployment was working fine until today i keep getting this error

**"Import Error urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips"**

I found that the urllib3 had an update on 2023-04-26 which removed the support of OpenSSL versions earlier than 1.1.1
The default OpenSSL installed on my build machine is v1.0.2

I've tried to install OpenSSL v1.1.1 using this command **yum install openssl11 openssl11-devel ** but i still get the same error
How can i recompile the 'ssl' module with the new version of the OpenSSL

buildspec.yml content

```
version: "0.2"
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - yum install openssl11 openssl11-devel ncurses-devel libffi-devel sqlite-devel.x86_64 readline-devel.x86_64 bzip2-devel.x86_64 -y
      - git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
      - python aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py
      - echo 'export PATH="/root/.ebcli-virtual-env/executables:$PATH"' >> ~/.bash_profile && source ~/.bash_profile
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean compile install
  post_build:
    commands:
      - echo "Entered Post build phase (deploy phase)"
      - eb init $AWS_EB_APP_NAME -r $AWS_EB_REGION
      - eb use $AWS_EB_ENV_NAME
      - eb deploy --staged -nh
artifacts:
  files:
    - target/*.jar
cache:
  paths:
    - "/root/.m2/**/*"

```
